In [1]:
import torch

x = torch.rand(2,2)
y = torch.rand(2,2)

# element-wise operations
z = torch.add(x,y)
z = torch.mul(x,y)

# y = y + x element-wise
y.add_(x)

print(x)
print(y)
print(z)

# view
x = torch.rand(4,4)
print(x)
y = x.view(16)
print(y)
y = x.view(-1, 8)
print(y.size())


tensor([[0.6709, 0.8830],
        [0.3393, 0.1578]])
tensor([[0.9611, 1.1458],
        [1.2470, 0.9823]])
tensor([[0.1947, 0.2320],
        [0.3080, 0.1301]])
tensor([[0.4396, 0.9160, 0.8195, 0.1488],
        [0.8592, 0.7503, 0.0295, 0.2445],
        [0.0686, 0.2243, 0.9831, 0.8840],
        [0.0936, 0.9774, 0.6000, 0.8758]])
tensor([0.4396, 0.9160, 0.8195, 0.1488, 0.8592, 0.7503, 0.0295, 0.2445, 0.0686,
        0.2243, 0.9831, 0.8840, 0.0936, 0.9774, 0.6000, 0.8758])
torch.Size([2, 8])
