In [1]:
import torch

In [4]:
# require_grad for those array that needs cal grad
x = torch.randn(3, requires_grad=True)
print(x)

y = x + 2
print(y)
z = y * y * 2
print(z)
# z = z.mean()        # z is scalar now, if comment this, backward would error unless use a para
print(z)
# backward()
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v)                         # same size, J * v - chain rule
# z.backward()        # dz/dx
print(x.grad)

tensor([ 1.3391, -0.2452,  0.5660], requires_grad=True)
tensor([3.3391, 1.7548, 2.5660], grad_fn=<AddBackward0>)
tensor([22.2997,  6.1585, 13.1688], grad_fn=<MulBackward0>)
tensor([22.2997,  6.1585, 13.1688], grad_fn=<MulBackward0>)
tensor([1.3357, 7.0191, 0.0103])


In [5]:
# no grad operation
x = torch.randn(3, requires_grad=True)
print(x)

# # 1.
# x.requires_grad_(False)             # _ -> inplace operation
# print(x)
# 
# # 2.
# y = x.detach()
# print(y)

# 3.
with torch.no_grad():
    y = x + 2
    print(y)

tensor([ 1.0201, -0.8884, -0.0540], requires_grad=True)
tensor([3.0201, 1.1116, 1.9460])


In [6]:
# grad accumulation
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights * 3).sum()          # grad should always be three
    model_output.backward()
    # weights.grad.zero_()                  # has to add this to zero the grads
    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])
